sudo: false

language: go

services:
  - docker

go:
  - "1.10.x"

go_import_path: 
  - $GOPATH/src

script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - make build
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make image-build image-publish DOCKER_IMAGE_VERSION=$TRAVIS_BRANCH

branches:
  only:
    - develop
    - /^feature\/.*$/
